### ISSUE TITLE
Refinery's blog engine does not allow duplicate titles, but WordPress does

### ISSUE THREAD

**Issue by ivanoats** [mremolt/refinerycms-wordpress-import#2]
So if your WordPress export contains posts with duplicate titles, the import will fail with a 'Validation failed: Title has already been taken' error

I am working on a pull request for this on my SustainableWebsites fork.  I am thinking I will wrap line 38 of lib/wordpress/post.rb with begin rescue end and then maybe just adding a ' 2'  to the title? I am just looking for a quick way to get my import done.

**Comment by mremolt** [comment]
That's perfect! More real wordpress dumps is what this gem needs. My projects simply didn't have duplicate titles. 

Hardcoding the 2 at the end of the title may cause the same problem. What if you got 3 post with the same title? 

What about using the post_id attribute? That one is unique and shouldn't cause any trouble. The idea with the rescue block is good.

**Comment by ivanoats** [comment]
Good idea with the post id, I'll work on that, thanks.

**Comment by mremolt** [comment]
Feature request is implemented. Have a look at the docs, as the ignore feature is now optional.
